require: rubocop-rspec

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Layout/LineLength:
  Max: 80

RSpec/MultipleExpectations:
  Max: 30

RSpec/ExampleLength:
  Max: 40