services:
  app:
    build: .
    container_name: app_web_server
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 3000:3000
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DB_POOL_SIZE: 5
      DB_TIMEOUT: 5
      HOST: http://app:3000
      SIDEKIQ_USERNAME: sidekiq
      SIDEKIQ_PASSWORD: sidekiq123
      RACK_ENV: development
    depends_on:
      - db
      - redis

  test_app:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: test_app_web_server
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    stdin_open: true
    environment:
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TEST_POSTGRES_DB}
      POSTGRES_HOST: test_db
      POSTGRES_PORT: 5432
      DB_POOL_SIZE: 5
      DB_TIMEOUT: 5
    depends_on:
      - test_db

  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: database
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432 
    volumes:
      - medical_exam_list_data:/var/lib/postgresql/data

  test_db:
    image: postgres:${POSTGRES_VERSION}
    container_name: test_database
    environment:
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TEST_POSTGRES_DB}
      POSTGRES_HOST: test_db
      POSTGRES_PORT: 5432

  cypress:
    build:
      dockerfile: Dockerfile.cypress
    image: cypress/included:13.3.3
    container_name: cypress
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    depends_on:
      - app
    environment:
      - CYPRESS_baseUrl=http://app:3000

  sidekiq:
    build: .
    command: bundle exec sidekiq -r ./app/workers/csv_import_worker.rb
    volumes:
      - .:/app
    depends_on:
      - app
      - redis
      - db
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgres://manager:pass123@db:5432/maindb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

  redis:
    image: redis:7.4.0
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

volumes:
  medical_exam_list_data: