services:
  app:
    build: .
    container_name: app_web_server
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 3000:3000
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DB_POOL_SIZE: 5
      DB_TIMEOUT: 5
    depends_on:
      - db

  test_app:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: test_app_web_server
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    stdin_open: true
    environment:
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TEST_POSTGRES_DB}
      POSTGRES_HOST: test_db
      POSTGRES_PORT: 5432
      DB_POOL_SIZE: 5
      DB_TIMEOUT: 5
    depends_on:
      - test_db

  db:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432 
    volumes:
      - medical_exam_list_data:/var/lib/postgresql/test_data

  test_db:
    image: postgres
    container_name: test_database
    environment:
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TEST_POSTGRES_DB}
      POSTGRES_HOST: test_db
      POSTGRES_PORT: 5432
    volumes:
      - medical_exam_list_test_data:/var/lib/postgresql/test_data

volumes:
  medical_exam_list_data:
  medical_exam_list_test_data: